name = "hr-dashboard-api"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[vars]
HR_ADMIN_EMAILS = "massimo@ticktockloans.com,zoe@ticktockloans.com"

[[d1_databases]]
binding = "hr_dashboard_db"
database_name = "hr_dashboard_db"
database_id = "afe6fdb3-ebd4-4ed2-8a24-ab43fddaba6f"